services:
  grafana:
    image: grafana/grafana:12.0.2
    volumes:
      - ./configs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./configs/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-storage:/var/lib/grafana
    environment:
      # Disable anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=false
      # Set default admin credentials
      - GF_SECURITY_ADMIN_USER=changeme
      - GF_SECURITY_ADMIN_PASSWORD=changeme123
      # Optional: Allow user sign up
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - librechat_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`sample.example.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=leresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - librechat_default
  tempo:
    image: grafana/tempo:2.8.1
    command:
      - -config.file=/etc/tempo.yaml
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
    networks:
      - librechat_default
networks:
  librechat_default:
    external: true
volumes:
  tempo-data:
  grafana-storage:
